### ISSUE TITLE
Relabel instructions are being output twice

### ISSUE THREAD

**Issue by zackspear** [benjamminf/craft-relabel#14]
Hey there! First of all thanks for this super handy plugin. Saves me from creating a bunch of one-off fields. 

As of yesterday, I ran into an issue where Relabel instructions are being outputted twice. Not sure what's causing it to happen.

![screen shot 2017-11-15 at 9 32 18 am](https://user-images.githubusercontent.com/2531682/32851245-52494654-c9e9-11e7-9566-afacb29e0e94.png)

Using:
- Craft CMS 2.6.2997
- PHP 7

The data seems to have a single instance of the instruction text.
![screenshot 2017-11-15 09 44 54](https://user-images.githubusercontent.com/2531682/32851663-727f6d30-c9ea-11e7-9b26-6f8ebdb9feda.jpg)

If you need any additional information, I'll be happy to provide it.

**Comment by ttempleton** [comment]
This was caused by the Relabel / Field Labels instruction being applied *per line* of the original field instruction, so it would duplicate if the original instruction was multi-line.

This has been fixed in Field Labels 1.0.6 by:
- Ensuring that the Field Labels instruction replaces the entire instruction, not just by line;
- Changing Field Labels' instruction input to a textarea, for consistency with Craft's presentation of instructions on a field settings page.
