### ISSUE TITLE
Project Config issue

### ISSUE THREAD

**Issue by rogertinch** [benjamminf/craft-relabel#20]
#### Description
I've been using Project Config the past few days to keep my local and remote setups in sync. I just installed Field Labels and deployed to fortrabbit and got an error after the sync installed the plugin. See screenshot:

![image](https://user-images.githubusercontent.com/11000310/55077663-48d02e80-5066-11e9-8a81-1895801f1284.png)

Running it again and I get a `done` message, but in the admin I'm not seeing my relabelled fields.

#### Steps to reproduce
1. Install plugin and relabel field instructions.
2. Deploy to remote.
3. Run project-config/sync

#### Other information
- Field Labels version: 1.0.2
- Craft CMS version: 3.1.19

**Comment by ttempleton** [comment]
Hi @tinchalamo, thanks for reporting.  The initial error with the project config sync from a terminal has been fixed in Field Labels 1.0.3.

I think that the lack of labels afterwards is actually because of the error having occurred, since the sync seems to be working fine after fixing the error -- can you please confirm by updating Field Labels and re-attempting a project config sync?

**Comment by rogertinch** [comment]
@ttempleton thanks for jumping on that so quickly! I updated the plugin and pushed it up, but my project config sync is still not working so the plugin never gets updated on production. I've got a few messages out to fortrabbit to see if they can do anything on their end.

**Comment by ttempleton** [comment]
@tinchalamo, have you been able to resolve the situation with Fortrabbit?

If not, I think if you can upload the [`vendor/spicyweb/craft-fieldlabels/src/Plugin.php`](https://raw.githubusercontent.com/spicywebau/craft-fieldlabels/1.0.3/src/Plugin.php) from 1.0.3 that should get things working again.

**Comment by ttempleton** [comment]
Closing this issue due to the relevant bug having been fixed.
